---
on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test
        run: bundle exec rspec

      - name: Build only
        if: ${{ github.ref != 'refs/heads/master' }}
        run: bundle exec rake build

      - name: Build and publish
        if: ${{ github.ref == 'refs/heads/master' }}
        run: bundle exec rake publish BUILD_DIR=build/api-catalogue
